version: 2.1
orbs:
  node: circleci/node@5.0.3
  slack: circleci/slack@4.10.1
  twilio: circleci/twilio@1.0.0
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
      - slack/notify:
          event: fail
          mentions: "@dibia"
          template: basic_fail_1
      - twilio/sendsms:
          body: Hi Twilio, you have reached the number of dibia27, How may I help you today?
      - twilio/alert:
          body: Twilio Unable to reach dibia27
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify